### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by toddrme2178** [berkerpeksag/selectors34#8]
I am trying to package selectors34
 for openSUSE. However, there is no license file I can find, either in the github or tarball. In order for people to know how they can use your code it is really important to have a license file. Would it be possible to add one? Thank you.

**Comment by berkerpeksag** [comment]
Thank you for packaging selectors34 for openSUSE. We basically need to copy https://github.com/python/cpython/blob/master/LICENSE and update `MANIFEST.in`. I don't have access to my development environment at the moment. Would you like submit a pull request?
